# Generated by Django 4.0.5 on 2023-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facility_health_facility_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
