# Generated by Django 4.0.5 on 2023-03-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facility_facility_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_code',
            field=models.CharField(default='FC111', max_length=100),
            preserve_default=False,
        ),
    ]
