# Generated by Django 4.0.5 on 2023-03-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_discharge', '0006_alter_patientdischarge_doctor'),
        ('treatment_outcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentoutcome',
            name='patient_discharge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='patients_discharge', to='patient_discharge.patientdischarge'),
            preserve_default=False,
        ),
    ]
