# Generated by Django 4.0.5 on 2023-03-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_discharge', '0006_alter_patientdischarge_doctor'),
        ('treatment_outcome', '0002_treatmentoutcome_patient_discharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentoutcome',
            name='patient_discharge',
            field=models.ForeignKey(help_text='patients discharge id', on_delete=django.db.models.deletion.PROTECT, related_name='patients_discharge', to='patient_discharge.patientdischarge'),
        ),
    ]
