# Generated by Django 4.0.5 on 2023-03-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_patient_hospital_record_no'),
        ('patient_service_charge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientservicecharge',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patiant_service_charges', to='person.patient'),
        ),
    ]
