# Generated by Django 4.0.5 on 2023-03-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_proceduretype_procedure_procedure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedure_types', to='procedure.proceduretype'),
        ),
    ]
