# Generated by Django 4.0.5 on 2023-03-29 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure', '0004_alter_procedure_created_by_alter_procedure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
