# Generated by Django 4.0.5 on 2023-03-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('procedure', '0005_alter_procedure_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_user', to='status.status'),
        ),
    ]
