# Generated by Django 4.0.5 on 2023-03-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_discharge', '0004_alter_patientdischarge_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischarge',
            name='treatment_outcome',
        ),
    ]
