# Generated by Django 4.0.5 on 2023-03-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_patient_hospital_record_no'),
        ('patient_discharge', '0005_remove_patientdischarge_treatment_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischarge',
            name='doctor',
            field=models.ForeignKey(help_text='this is a staff', on_delete=django.db.models.deletion.PROTECT, related_name='patient_discharge_doctor', to='person.staff'),
        ),
    ]
