# Generated by Django 4.0.5 on 2023-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='digital_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' Digital Address'),
        ),
    ]
