# Generated by Django 4.0.5 on 2023-03-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_diagnosis', '0003_consultationdiagnosis_ipd'),
        ('sponsor', '0002_sponsor_scheme_code'),
        ('radiology_procedure_request', '0002_alter_radiologyprocedurerequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologyprocedurerequest',
            name='consultation',
        ),
        migrations.AddField(
            model_name='radiologyprocedurerequest',
            name='consultation_diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_radiology_procedure_request', to='consultation_diagnosis.consultationdiagnosis'),
        ),
        migrations.AddField(
            model_name='radiologyprocedurerequest',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rediolo_procedure_sponsor', to='sponsor.sponsor'),
        ),
    ]
