# Generated by Django 4.0.5 on 2023-03-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology_procedure_request', '0003_remove_radiologyprocedurerequest_consultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologyprocedurerequest',
            name='consultation_diagnosis',
        ),
        migrations.RemoveField(
            model_name='radiologyprocedurerequest',
            name='sponsor',
        ),
    ]
